### ISSUE TITLE
Project Needs a license!

### ISSUE THREAD

**Issue by bsmithgall** [UCSUR-Pitt/wprdc-etl#22]
@rgradeck @saylorsd should work on this.

**Comment by saylorsd** [comment]
@bsmithgall Just spoke with @rgradeck about this.  He'd like to go as nonrestrictive as possible unless you have an objections.  He suggested MIT, which works for me. If that works for you, I'll find a specific version and add it to the project.

**Comment by bsmithgall** [comment]
:+1:

**Comment by saylorsd** [comment]
We'll need to wait until we have some clarification from the University as @rgradeck and I have signed IP agreements. I'll make a pull request to fix this issue once we're good to go.
