### ISSUE TITLE
Write extractor for remote HTTP resources

### ISSUE THREAD

**Issue by bsmithgall** [UCSUR-Pitt/wprdc-etl#32]

**Comment by bsmithgall** [comment]
An interesting question is whether or not this should be related to #17, insofar as it involves a `connection` and then a separate `extraction`.

**Comment by saylorsd** [comment]
I feel like it's  a related issue.  We'll have various combinations of `connection` and `extraction` -- enough to justify not creating an `extractor` for each possible combo.  Do you think mixins would be a solution?  If so, would it be taht each extractor just inherit from a `connection` mixin?

**Comment by saylorsd** [comment]
@bsmithgall I believe this was fixed a while ago with the creation of `HTTPConenctor` and `RemoteFileConnector`  I'm going to close this unless you have any objections.
