### ISSUE TITLE
Finish documentation and add project to readthedocs

### ISSUE THREAD

**Issue by bsmithgall** [UCSUR-Pitt/wprdc-etl#40]

**Comment by bsmithgall** [comment]
@saylorsd FYI as you continue to write docs and docstrings, please make sure they follow the [proper format](https://pythonhosted.org/an_example_pypi_project/sphinx.html#full-code-example)

**Comment by bsmithgall** [comment]
Project is now on readthedocs: https://wprdc-etl.readthedocs.org/en/latest/

@saylorsd in the repo's settings, you should be able to add readthedocs as a service so that it will automatically build when master is updated.

**Comment by saylorsd** [comment]
:+1: Awesome! And the readthedocs service is now added.
